version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 13.0.0
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: make test

  build: 
    macos:
      xcode: 13.0.0
    steps: 
      - checkout
      - run:
          name: Build Application
          command: make build
      # - run:
      #     name: Archive Application
      #     command: make archive
      # - run:
      #    name: Compress app for storage
      #    command: zip -r app.zip build/mac/Pareto Security.app
      # - store_artifacts:
      #    path: app.zip
      #    destination: app
          
workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test