name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift:
    name: Lint
    runs-on: macos-11
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Lint
      run: swiftlint
  build:
    name: Build
    runs-on: macos-11
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build
      run: make build archive
  test:
    name: Unit Tests
    runs-on: macos-11
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Tests
      run: make test
