name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift:
    name: Lint
    runs-on: macos-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Lint
      run: swiftlint
  mac:
     name: Test and build
     runs-on: macos-latest
     steps:
     - name: Repository checkout
       uses: actions/checkout@v2
     - name: Build
       uses: sersoft-gmbh/xcodebuild-action@v1
       with:
         project: Pareto Security.xcodeproj
         scheme: Pareto Security
         destination: platform=macOS
         action: build
     - name: Test
       uses: sersoft-gmbh/xcodebuild-action@v1
       with:
         project: Pareto Security.xcodeproj
         scheme: Pareto Security
         destination: platform=macOS
         action: test
